version: '3.9'
volumes:
 database:

services:
#  web:
#    build: docker/symfony
#    volumes:
#      - ./symfony:/var/www/html
#    ports:
#      - '8081:80'
#    environment:
#      APACHE_DOCUMENT_ROOT: /var/www/html/public
##    networks:
##      - web
##      - database
#    depends_on:
#      - database
  gateway:
    build:
      context: docker/symfony
      args:
        SERVICE_NAME: gateway
    volumes:
      - ./gateway:/var/www/html
    ports:
      - '8081:80'
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - rabbitmq

  users:
    build:
      context: docker/symfony
      args:
        SERVICE_NAME: users
    volumes:
      - ./users:/var/www/html
    ports:
      - '8082:80'
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - database
      - rabbitmq

  posts:
    build:
      context: docker/symfony
      args:
        SERVICE_NAME: posts
    volumes:
      - ./posts:/var/www/html
    ports:
      - '8083:80'
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - database
      - rabbitmq

  likes:
    build:
      context: docker/symfony
      args:
        SERVICE_NAME: likes
    volumes:
      - ./likes:/var/www/html
    ports:
      - '8084:80'
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - database
      - rabbitmq

  direct_coms:
    build:
      context: docker/symfony
      args:
        SERVICE_NAME: direct_coms
    volumes:
      - ./direct_coms:/var/www/html
    ports:
      - '8085:80'
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - database
      - rabbitmq

  database:
     build: docker/postgres
     ports:
         - "6432:5432"
     environment:
       - POSTGRES_PASSWORD=psql
       - POSTGRES_USER=psql
       - POSTGRES_DB=database
       - PGDATA=/var/lib/postgresql/data/pgdata
     volumes:
         - database:/var/lib/postgresql/data/pgdata

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest