version: '3.9'
volumes:
 database:

services:
#  web:
#    build: docker/symfony
#    volumes:
#      - ./symfony:/var/www/html
#    ports:
#      - '8081:80'
#    environment:
#      APACHE_DOCUMENT_ROOT: /var/www/html/public
##    networks:
##      - web
##      - database
#    depends_on:
#      - database
  gateway:
    build: docker/symfony
    volumes:
      - ./gateway:/var/www/html
    ports:
      - '8081:80'
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public

  users:
    build: docker/symfony
    volumes:
      - ./users:/var/www/html
    ports:
      - '8082:80'
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - database

  posts:
    build: docker/symfony
    volumes:
      - ./posts:/var/www/html
    ports:
      - '8083:80'
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - database

  likes:
    build: docker/symfony
    volumes:
      - ./likes:/var/www/html
    ports:
      - '8084:80'
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - database

  direct_coms:
    build: docker/symfony
    volumes:
      - ./direct_coms:/var/www/html
    ports:
      - '8085:80'
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - database

  database:
     build: docker/postgres
     ports:
         - "6432:5432"
     environment:
       - POSTGRES_PASSWORD=psql
       - POSTGRES_USER=psql
       - POSTGRES_DB=database
       - PGDATA=/var/lib/postgresql/data/pgdata
     volumes:
         - database:/var/lib/postgresql/data/pgdata