services:
  app.event.jwt_created_listener:
    class: App\EventListener\JWTCreatedListener
    arguments: [ '@Symfony\Bundle\SecurityBundle\Security' ]
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }